[project]
name = "prog6-kmeans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.6.0",
    "numpy>=1.19.5",
    "scikit-learn>=1.1.2",
]
